= 0 - A confession
:description: A simple guide to Bash
:keywords: bash, shell, programming, code, script
:stylesdir: styles
:stylesheet: adoc-github.css

I had trouble learning Bash.
I found that I could never remember how to write simple things like an if statement.
It didn't follow the patterns I'd learnt from other programming languages.
I had questions like _why can't I use a variable in my if statements_?
Picking up ad-hoc information via Google never provided a consistent framework.
It was only when I read parts of the https://www.gnu.org/software/bash/manual/html_node/index.html[GNU Bash manual], that things clicked.
This guide will help you understand the fundamentals of Bash a little better.
A lot of programmers struggle with it because it breaks all the patterns learnt in more structured languages.

One thing that will happen after reading the first few sections in this guide: +

- You'll understand why if statements don't work like if statements in other languages, and therefore:
- You will never forget how to write an if statment in Bash.

I believe that writing an if statement is such a fundamental problem for most programmers using Bash that you owe it to yourself to read the first few sections of this guide.
It will change your life!

To begin you'll need: +

- a Unix based operating system like a Mac or Linux machine
- a text editor

Some notes: +

- I don't differentiate between shell and Bash. This is to keep this document simple. It adds a lot
  of extra work to differentiate POSIX compliant shell from Bash and for most people it's not
  relevant.

