= Tiny Beautiful Things
:description: Review of Tiny Beautiful Things
:keywords: Cheryl Strayed, self-help
:stylesheet: readthedocs.css


Empathetic without being saccharine (ok maybe it is a bit), honest advice
without preaching, she manages to walk the line between brutal honesty and
toxic positivity.

I’ve been charmed by this book. Beneath the empathetic writing, the underlying
theme of taking responsibility, even when it's not your fault and something or
someone else has transgressed, seeps through. Like the ice beneath the iceberg,
you know it’s there. It’s never preached but rather felt. And therein lies the
books power; its ability to move you towards ownership of your troubles, not by
the whip-like force of logic, but more like the gently nudged leaf floating in
a stream. This is powerful because much of the book is dealing with personal
traumas; divorce, break-ups, death, sexual abuse, and other complex
relationship matters, where accidents happen and parties involved are left with
nobody to blame and a problem to own.

If you know a person lost in a victimhood mentality where everything that
happens to them is somebody else’s fault, then point them to this book.

